services:

  frontend:
    build: ./game
    container_name: mkjs-frontend

    ports:
      - "8080:80"

  backend:
    build: ./server
    container_name: mkjs-backend

    ports:
      - "55555:55555"

    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: postgres

    environment:
      POSTGRES_USER: mkjs
      POSTGRES_PASSWORD: mkjs123
      POSTGRES_DB: mkjsdb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: